In [2]:
import pandas as pd
import numpy as np
import requests

In [3]:
url= "https://raw.githubusercontent.com/rohan-r-kulkarni/bigtech_randomforest/main/data.csv"
df = pd.read_csv(url)
df1=df.reset_index()
df1

,index,Unnamed: 0,AAPL US Equity,AAPL US Equity.1,AAPL US Equity.2,AAPL US Equity.3,AAPL US Equity.4,AAPL US Equity.5,AAPL US Equity.6,AAPL US Equity.7,...,SPX Index.1,SPX Index.2,SPX Index.3,SPX Index.4,SPX Index.5,SPX Index.6,SPX Index.7,SPX Index.8,SPX Index.9,SPX Index.10
0,0,NaN,1,2,3,4,5,6,7,8,...,2,3,4,5,6,7,8,9,10,11
1,1,Dates,PX_OPEN,PX_OFFICIAL_CLOSE,PE_RATIO,EV_EBITDA_ADJUSTED,SALES_GROWTH,CUR_MKT_CAP,PX_VOLUME,FREE_CASH_FLOW_YIELD,...,PX_OFFICIAL_CLOSE,PE_RATIO,EV_EBITDA_ADJUSTED,SALES_GROWTH,CUR_MKT_CAP,PX_VOLUME,FREE_CASH_FLOW_YIELD,PROF_MARGIN,EBITDA_TO_REVENUE,BEST_PX_SALES_RATIO
2,2,1/3/00,0.936,NaN,39.6143,NaN,37.0175,17999.4376,535819200,5.1223,...,NaN,28.1209,NaN,NaN,NaN,1071554100,2.99,7.61,NaN,NaN
3,3,1/4/00,0.967,NaN,36.2744,NaN,37.0175,16481.8971,511728000,5.5939,...,NaN,28.1744,NaN,NaN,NaN,1264023700,2.99,7.61,NaN,NaN
4,4,1/5/00,0.926,NaN,36.8052,NaN,37.0175,16723.0956,778321600,5.5133,...,NaN,28.2119,NaN,NaN,NaN,1177726200,2.98,7.61,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5977,5977,11/28/22,145.14,144.22,23.6039,18.0919,8.1406,2294268.778,69346522,4.754,...,NaN,19.1332,NaN,NaN,34556774.68,517449991,4.95,11.17,NaN,2.2736
5978,5978,11/29/22,144.29,141.17,23.1047,18.0919,8.1406,2245749.018,83763803,4.8567,...,NaN,19.7254,NaN,NaN,35624829.34,1406250061,4.8,11.17,NaN,2.343
5979,5979,11/30/22,141.395,148.03,24.2275,18.0919,8.1406,2354878.708,111380880,4.6316,...,NaN,19.7083,NaN,NaN,35596739.87,633969105,4.8,11.17,NaN,2.3389
5980,5980,12/1/22,148.21,148.31,24.2733,18.0919,8.1406,2359332.981,71250416,4.6229,...,NaN,19.6847,NaN,NaN,35596739.87,633969105,4.81,11.17,NaN,2.336
5981,5981,12/2/22,145.96,148.31,24.1915,18.0919,8.1406,2351378.883,65156858,4.6385,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df1.columns

Index(['index', 'Unnamed: 0', 'AAPL US Equity', 'AAPL US Equity.1',
       'AAPL US Equity.2', 'AAPL US Equity.3', 'AAPL US Equity.4',
       'AAPL US Equity.5', 'AAPL US Equity.6', 'AAPL US Equity.7',
       ...
       'SPX Index.1', 'SPX Index.2', 'SPX Index.3', 'SPX Index.4',
       'SPX Index.5', 'SPX Index.6', 'SPX Index.7', 'SPX Index.8',
       'SPX Index.9', 'SPX Index.10'],
      dtype='object', length=123)

In [5]:
df2=df1.rename(columns={"Unnamed: 0": "Dates"})
dates=df2.loc[2:, ["Dates"]].reset_index(drop=True)
dates

         Dates
0       1/3/00
1       1/4/00
2       1/5/00
3       1/6/00
4       1/7/00
...        ...
5975  11/28/22
5976  11/29/22
5977  11/30/22
5978   12/1/22
5979   12/2/22

[5980 rows x 1 columns]

In [6]:
spx_i = 10
spx_df = pd.DataFrame(df2.iloc[1: , 2+11*spx_i:].reset_index(drop=True))
spx_df.columns = spx_df.iloc[0, :]
#spx_df.columns = spx_df.loc[1, :]
spx_df = pd.DataFrame(spx_df.iloc[1:, 0]).reset_index(drop=True)
spx_df

      PX_OPEN
0     1455.22
1     1399.42
2     1402.11
3     1403.45
4     1441.47
...       ...
5975  3964.19
5976  3957.18
5977  4087.14
5978  4040.17
5979      NaN

[5980 rows x 1 columns]

In [17]:
stocks = {}
names=[]
drop = ["SALES_GROWTH", "PROF_MARGIN", "EBITDA_TO_REVENUE","EV_EBITDA_ADJUSTED"]
for i in range(0, 10):
    this_name = df2.columns[2+11*i].split(" ")[0]

    this_df = df2.iloc[1: , 2+11*i:13+11*i].reset_index(drop=True)
    this_df.columns = this_df.loc[0, :]
    this_df = this_df.drop(drop, axis = 1)
    this_df = this_df.loc[1:, :].reset_index(drop=True)
    this_df = pd.concat([dates, this_df], axis=1)
    this_df = this_df.dropna()
    
#     d1 = this_df[['Dates', 'PX_OPEN', 'PE_RATIO', 'CUR_MKT_CAP',
#         'PX_VOLUME', 'FREE_CASH_FLOW_YIELD', 'BEST_PX_SALES_RATIO']]
#     d2 = this_df[['Dates','PX_OFFICIAL_CLOSE']]
    
#     this_df = d1.join(d2, on=Dates)

    this_df = this_df.reindex(['Dates', 'PX_OPEN', 'PE_RATIO', 'CUR_MKT_CAP',
        'PX_VOLUME', 'FREE_CASH_FLOW_YIELD', 'BEST_PX_SALES_RATIO','PX_OFFICIAL_CLOSE'],axis=1)

    
    if len(this_df) < 500:
        continue # do not include stocks with too small df
    
    stocks[this_name] = this_df
#     stocks[this_name] = test
    
    
stocks

{'AAPL':          Dates  PX_OPEN PE_RATIO  CUR_MKT_CAP  PX_VOLUME FREE_CASH_FLOW_YIELD  \
 5181  11/12/19   65.388  22.0784  1163957.699   87388904               4.8602
 5182  11/13/19   65.283  22.2899  1175110.295  103270372               4.8141
 5183  11/14/19   65.938  22.1357   1166979.12   89582224               4.8476
 5184  11/15/19    65.92  22.3987  1180842.106  100374664               4.7907
 5185  11/18/19    66.45  22.5116  1186796.082   86803588               4.7666
 ...        ...      ...      ...          ...        ...                  ...
 5975  11/28/22   145.14  23.6039  2294268.778   69346522                4.754
 5976  11/29/22   144.29  23.1047  2245749.018   83763803               4.8567
 5977  11/30/22  141.395  24.2275  2354878.708  111380880               4.6316
 5978   12/1/22   148.21  24.2733  2359332.981   71250416               4.6229
 5979   12/2/22   145.96  24.1915  2351378.883   65156858               4.6385

      BEST_PX_SALES_RATIO PX_OFFICIAL_CLOSE
 5181               3.592             65.49
 5182               3.627            66.118
 5183               3.602             65.66
 5184               3.644             66.44
 5185               3.663            66.775
 ...                  ...               ...
 5975               5.669            144.22
 5976               5.553            141.17
 5977               5.829            148.03
 5978                5.84            148.31
 5979                5.82            148.31

 [799 rows x 8 columns],
 'META':          Dates  PX_OPEN PE_RATIO  CUR_MKT_CAP PX_VOLUME FREE_CASH_FLOW_YIELD  \
 5171  10/29/19   189.56  23.4485  537067.9312  28734559               3.6331
 5172  10/30/19    196.7   23.872  546537.2227  42286529               3.5687
 5173  10/31/19   192.85  24.1173  552155.1633  21711829               3.5324
 5174   11/1/19   194.55  24.2544  555292.0845  16371292               3.5124
 5175   11/4/19   195.37  24.2045  554151.3859   9941954               3.5197
 ...        ...      ...      ...          ...       ...                  ...
 5974  11/25/22   110.78  10.2522  288435.4648  23332816               8.8274
 5975  11/28/22   109.54  10.3163  290238.5179  23899238               8.7726
 5976  11/29/22  109.505  11.1306  313147.8984  43348557               8.1308
 5977  11/30/22  119.198  11.3512  319352.5223  36551374               7.9728
 5978   12/1/22   117.83  11.6386  327439.7401  39685113               7.7759

      BEST_PX_SALES_RATIO PX_OFFICIAL_CLOSE
 5171                3.79            188.25
 5172               3.857            191.65
 5173               3.897            193.62
 5174               3.919            194.72
 5175               3.911            194.32
 ...                  ...               ...
 5974               2.441            108.78
 5975               2.457            109.46
 5976               2.651             118.1
 5977               2.703            120.44
 5978               2.772            120.44

 [808 rows x 8 columns],
 'AMZN':          Dates PX_OPEN PE_RATIO  CUR_MKT_CAP  PX_VOLUME FREE_CASH_FLOW_YIELD  \
 5184  11/15/19  86.915  77.6143   868899.502   56838140               2.3277
 5185  11/18/19   87.85  77.6258  869028.4092   45490700               2.3274
 5186  11/19/19  87.457  77.3043  865428.9214   55875180                2.337
 5187  11/20/19   87.15  76.8251  860064.3955   53258760               2.3516
 5188  11/21/19  86.951  77.3127  865523.1229   49581620               2.3368
 ...        ...     ...      ...          ...        ...                  ...
 5974  11/25/22   93.93  94.3518  958445.4098   75062316              -2.7514
 5975  11/28/22   94.04  92.8153  942836.8789   65567286               -2.797
 5976  11/29/22   92.47  96.9529  984867.6942  102805806              -2.6776
 5977  11/30/22   96.99  95.9084  974257.9738   68487969              -2.7067
 5978   12/1/22  94.475  94.5326  960281.6796   70409267              -2.7461

      BEST_PX_SALES_RATIO PX_OFFICIAL_CLOSE
 5184               1.643            87.627
 5185               1.643             87.64
 5186               1.636            87.277
 5187               1.626            86.736
 5188               1.636            87.286
 ...                  ...               ...
 5974               1.757             93.95
 5975               1.728             92.42
 5976               1.805             96.54
 5977               1.786              95.5
 5978                1.76              95.5

 [795 rows x 8 columns],
 'NFLX':          Dates  PX_OPEN PE_RATIO  CUR_MKT_CAP PX_VOLUME FREE_CASH_FLOW_YIELD  \
 5162  10/16/19   304.49   93.722  128438.8626  38462343              -2.2432
 5163  10/17/19   289.36  87.9553  120650.5799  23449638              -2.3902
 5164  10/18/19   272.89  88.8339  121855.7709  12633959              -2.3666
 5165  10/21/19  271.159  85.2045  116877.2363  11865593              -2.4674
 5166  10/22/19   268.06  86.6677  118884.4272   7154430              -2.4257
 ...        ...      ...      ...          ...       ...                  ...
 5974  11/25/22      284  29.3455  125126.4123   4707049               0.5728
 5975  11/28/22    282.5  29.3236   125032.958   5786874               0.5733
 5976  11/29/22   281.37   31.888  135967.1115  16070120               0.5272
 5977  11/30/22   303.99  33.0799  141049.2456  14664866               0.5082
 5978   12/1/22   310.49   33.441  142589.0181  12633736               0.5027

      BEST_PX_SALES_RATIO PX_OFFICIAL_CLOSE
 5162               3.482            293.35
 5163               3.271             275.3
 5164               3.304            278.05
 5165               3.169            266.69
 5166               3.223            271.27
 ...                  ...               ...
 5974                3.78            281.17
 5975               3.777            280.96
 5976               4.107            305.53
 5977               4.261            316.95
 5978               4.307            316.95

 [817 rows x 8 columns],
 'TSLA':          Dates PX_OPEN   PE_RATIO  CUR_MKT_CAP  PX_VOLUME  \
 5280   3/30/20  33.417  3314.4628   96473.4231  266572275
 5281   3/31/20    33.6  3046.0166   88659.8122  200297700
 5282    4/1/20  32.069   2874.664   83672.2835  297876405
 5283    4/2/20  33.967  3036.2124   88374.4424  338431140
 5284    4/3/20   34.08  3265.3784   95044.7327  223527540
 ...        ...     ...        ...          ...        ...
 5974  11/25/22  179.96    55.9552   577616.078   93038148
 5975  11/28/22  184.99    55.3159  571016.3754   83357111
 5976  11/29/22  182.43    59.5587  614814.4018  109186404
 5977  11/30/22  197.08    59.5587  614814.4018   80046213
 5978   12/1/22  191.78    59.6077  615319.6441   73262812

      FREE_CASH_FLOW_YIELD BEST_PX_SALES_RATIO PX_OFFICIAL_CLOSE
 5280                1.199               1.461            34.933
 5281               1.3047               1.342            32.104
 5282               1.3825                1.27            30.298
 5283               1.3089               1.341            32.001
 5284                1.217               1.442            34.416
 ...                   ...                 ...               ...
 5974               1.5729               5.201            182.92
 5975               1.5911               5.141            180.83
 5976               1.4778               5.536             194.7
 5977               1.4778               5.537             194.7
 5978               1.4765               5.541             194.7

 [699 rows x 8 columns],
 'MSFT':          Dates PX_OPEN PE_RATIO  CUR_MKT_CAP PX_VOLUME FREE_CASH_FLOW_YIELD  \
 5181  11/12/19  146.74  29.6838  1123799.356  17444230               3.4246
 5182  11/13/19  147.02   29.835   1129520.96  19755100               3.4072
 5183  11/14/19  148.93  30.2199  1144091.979  23508807               3.3638
 5184  11/15/19  150.07  30.2944  1146914.637  21554762               3.3556
 5185  11/18/19  150.88  30.3045  1147296.077  23960164               3.3544
 ...        ...     ...      ...          ...       ...                  ...
 5974  11/25/22  246.08  26.0503  1802193.427  24810271               3.5024
 5975  11/28/22   241.4  25.8963  1791533.531  17956313               3.5233
 5976  11/29/22  240.57  27.4921  1901934.278  47594239               3.3188
 5977  11/30/22  253.87  27.4436  1898579.765  26041524               3.3246
 5978   12/1/22  249.82  27.4792  1901039.773  21270934               3.3203

      BEST_PX_SALES_RATIO PX_OFFICIAL_CLOSE
 5181               5.673            147.31
 5182               5.702            148.06
 5183               5.776            149.97
 5184                5.79            150.34
 5185               5.792            150.39
 ...                  ...               ...
 5974               8.242            241.76
 5975               8.216            240.33
 5976               8.722            255.14
 5977               8.708            254.69
 5978               8.719            254.69

 [798 rows x 8 columns],
 'IBM':          Dates   PX_OPEN PE_RATIO  CUR_MKT_CAP PX_VOLUME FREE_CASH_FLOW_YIELD  \
 5360   7/20/20  125.2793    10.48  111927.6601  15364948              11.9227
 5361   7/21/20  120.2551   10.697  114245.0581   8195366              11.6809
 5362   7/22/20  123.3117  10.5856  113055.2829   4220136              11.8038
 5363   7/23/20  120.8091  10.4576  111687.9293   3531076              11.9483
 5364   7/24/20  119.2618  10.4925  112060.8439   3733547              11.9086
 ...        ...       ...      ...          ...       ...                  ...
 5974  11/25/22    147.98  17.8174  132165.1917   3538696               5.7955
 5975  11/28/22    145.91  17.8552  132445.4709   2754744               5.7832
 5976  11/29/22    146.19  18.1489  134624.4155   6377582               5.6896
 5977  11/30/22    149.98  18.1806  134859.4883   4495924               5.6797
 5978   12/1/22    148.13  18.1209  134416.4647   2868387               5.6984

      BEST_PX_SALES_RATIO PX_OFFICIAL_CLOSE
 5360               1.513           120.408
 5361               1.544           122.901
 5362               1.528           121.621
 5363                1.51          120.1501
 5364               1.515          120.5512
 ...                  ...               ...
 5974               2.212            146.18
 5975               2.217            146.49
 5976               2.253             148.9
 5977               2.257            149.16
 5978               2.252            149.16

 [619 rows x 8 columns],
 'INTC':          Dates PX_OPEN PE_RATIO  CUR_MKT_CAP PX_VOLUME FREE_CASH_FLOW_YIELD  \
 5428  10/22/20   48.35   9.8928     197523.6  97322490               9.9112
 5429  10/23/20   47.85    9.589    191458.56  54161291              10.2252
 5430  10/26/20   45.98   9.3674    187032.72  50130518              10.4671
 5431  10/27/20   44.89   9.0821     181336.5  45066011              10.7959
 5432  10/28/20   44.24   9.0533    180762.78  36796801              10.8302
 ...        ...     ...      ...          ...       ...                  ...
 5974  11/25/22    29.1  15.1098   118548.075  28282116             -11.4092
 5975  11/28/22   28.85  15.2018     119270.3  24361493             -11.3402
 5976  11/29/22   28.77  15.8173    124098.89  72072532             -10.8989
 5977  11/30/22   30.24   15.691    123108.41  38896309             -10.9866
 5978   12/1/22   29.17  15.4701  121375.0694  30611643             -11.1435

      BEST_PX_SALES_RATIO PX_OFFICIAL_CLOSE
 5428               2.844              48.2
 5429               2.757             46.72
 5430               2.694             45.64
 5431               2.612             44.25
 5432               2.604             44.11
 ...                  ...               ...
 5974               2.002            28.725
 5975               2.014              28.9
 5976               2.096             30.07
 5977               2.079             29.83
 5978                2.05             29.83

 [551 rows x 8 columns]}

<h1> Data processing done </h1>
<h2> Now do AAPL </h2>

In [18]:
s = "TSLA"

In [19]:
stocks[s]= stocks[s].set_index("Dates")
stocks[s] = stocks[s].astype(float)
# test=appl['Dates', 'PX_OPEN', 'PE_RATIO', 'CUR_MKT_CAP',
#        'PX_VOLUME', 'FREE_CASH_FLOW_YIELD', 'BEST_PX_SALES_RATIO']

In [20]:
stocks[s]

,PX_OPEN,PE_RATIO,CUR_MKT_CAP,PX_VOLUME,FREE_CASH_FLOW_YIELD,BEST_PX_SALES_RATIO,PX_OFFICIAL_CLOSE
Dates,,,,,,,
3/30/20,33.417,3314.4628,96473.4231,266572275.0,1.1990,1.461,34.933
3/31/20,33.600,3046.0166,88659.8122,200297700.0,1.3047,1.342,32.104
4/1/20,32.069,2874.6640,83672.2835,297876405.0,1.3825,1.270,30.298
4/2/20,33.967,3036.2124,88374.4424,338431140.0,1.3089,1.341,32.001
4/3/20,34.080,3265.3784,95044.7327,223527540.0,1.2170,1.442,34.416
...,...,...,...,...,...,...,...
11/25/22,179.960,55.9552,577616.0780,93038148.0,1.5729,5.201,182.920
11/28/22,184.990,55.3159,571016.3754,83357111.0,1.5911,5.141,180.830
11/29/22,182.430,59.5587,614814.4018,109186404.0,1.4778,5.536,194.700
11/30/22,197.080,59.5587,614814.4018,80046213.0,1.4778,5.537,194.700
12/1/22,191.780,59.6077,615319.6441,73262812.0,1.4765,5.541,194.700

In [21]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer, make_column_transformer

preprocess = make_column_transformer(
    (StandardScaler(),[
        'PE_RATIO', 
        'CUR_MKT_CAP', 
        'PX_VOLUME', 
        'FREE_CASH_FLOW_YIELD', 
        'BEST_PX_SALES_RATIO'
    ])

)

X = preprocess.fit_transform(stocks[s])
X

array([[ 1.73741621, -2.10805951,  1.97338691,  1.93120268, -2.00518819],
       [ 1.54622352, -2.13692683,  1.11161946,  2.29632507, -2.04655037],
       [ 1.4241828 , -2.15535321,  2.38043412,  2.56507173, -2.07157623],
       ...,
       [-0.58079094, -0.19305325, -0.07309957,  2.89426912, -0.58879431],
       [-0.58079094, -0.19305325, -0.4520091 ,  2.89426912, -0.58844672],
       [-0.58075604, -0.19118664, -0.54021358,  2.8897785 , -0.5870564 ]])

In [96]:
day_change = stocks[s].loc[:,"PX_OFFICIAL_CLOSE"] - stocks[s].loc[:,"PX_OPEN"] #close - open
buy_indicator = (day_change>0).astype(int).shift(1) #True = BUY, False = SELL
stocks[s]=stocks[s].assign(day_change=day_change)
stocks[s]=stocks[s].assign(buy_indicator=buy_indicator)

stocks[s] = stocks[s].dropna()
buy_indicator = buy_indicator.dropna()
stocks[s]

,PX_OPEN,PE_RATIO,CUR_MKT_CAP,PX_VOLUME,FREE_CASH_FLOW_YIELD,BEST_PX_SALES_RATIO,PX_OFFICIAL_CLOSE,day_change,buy_indicator
Dates,,,,,,,,,
4/6/20,36.333,3450.1407,100422.5737,268796760.0,1.1519,1.524,36.363,0.030,1.0
4/7/20,36.947,3471.5835,101046.7052,189840360.0,1.1447,1.533,36.589,-0.358,1.0
4/8/20,37.473,3624.4030,105494.7928,204750000.0,1.0965,1.601,38.200,0.727,0.0
4/9/20,37.473,3624.4030,105494.7928,204750000.0,1.0965,1.601,38.200,0.727,1.0
4/10/20,39.344,4117.4610,119846.1350,337131315.0,0.9652,1.819,43.397,4.053,1.0
...,...,...,...,...,...,...,...,...,...
11/25/22,179.960,55.9552,577616.0780,93038148.0,1.5729,5.201,182.920,2.960,0.0
11/28/22,184.990,55.3159,571016.3754,83357111.0,1.5911,5.141,180.830,-4.160,1.0
11/29/22,182.430,59.5587,614814.4018,109186404.0,1.4778,5.536,194.700,12.270,0.0
11/30/22,197.080,59.5587,614814.4018,80046213.0,1.4778,5.537,194.700,-2.380,1.0
12/1/22,191.780,59.6077,615319.6441,73262812.0,1.4765,5.541,194.700,2.920,0.0

In [97]:
#unscaled x
x = stocks[s].iloc[:, 1:6]
x

,PE_RATIO,CUR_MKT_CAP,PX_VOLUME,FREE_CASH_FLOW_YIELD,BEST_PX_SALES_RATIO
Dates,,,,,
4/6/20,3450.1407,100422.5737,268796760.0,1.1519,1.524
4/7/20,3471.5835,101046.7052,189840360.0,1.1447,1.533
4/8/20,3624.4030,105494.7928,204750000.0,1.0965,1.601
4/9/20,3624.4030,105494.7928,204750000.0,1.0965,1.601
4/10/20,4117.4610,119846.1350,337131315.0,0.9652,1.819
...,...,...,...,...,...
11/25/22,55.9552,577616.0780,93038148.0,1.5729,5.201
11/28/22,55.3159,571016.3754,83357111.0,1.5911,5.141
11/29/22,59.5587,614814.4018,109186404.0,1.4778,5.536
11/30/22,59.5587,614814.4018,80046213.0,1.4778,5.537
12/1/22,59.6077,615319.6441,73262812.0,1.4765,5.541

In [98]:
from sklearn.model_selection import train_test_split
#Get x_train, x_test, y_train, y_test

x_train, x_test, y_train, y_test = train_test_split(x, buy_indicator, test_size = 0.3, train_size = 0.7, random_state=42)
#And check the shape
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(485, 5) (485,)
(209, 5) (209,)

<h3> RF classifier </h3>

In [99]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=42,n_estimators=80,max_depth=10,min_samples_leaf=1000,min_samples_split=4000)
rf.fit(x_train,y_train.astype(int))

RandomForestClassifier(max_depth=10, min_samples_leaf=1000,
                       min_samples_split=4000, n_estimators=80,
                       random_state=42)

In [100]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score,recall_score,precision_score
from sklearn.metrics import average_precision_score,roc_auc_score

y_test_pred = rf.predict(x_test)
cfm = confusion_matrix(y_test,y_test_pred)

accuracy_training = rf.score(x_train,y_train)
accuracy_testing = rf.score(x_test,y_test)

precision = precision_score(y_test, y_test_pred)
recall = recall_score(y_test, y_test_pred)
f1 = f1_score(y_test, y_test_pred)

y_prob = rf.predict_proba(x_test)[:,1]
auc = roc_auc_score(y_test, y_prob)

ap = average_precision_score(y_test, y_test_pred)

print("Confusion Matrix: \n",cfm)
print("Training accuracy: ",accuracy_training)
print("Testing  accuracy: ",accuracy_testing)
print("Precision: ",precision)
print("Recall: ",recall)
print("F1-Score: ",f1)
print("AUC: ",auc)
print("Average Precision: ",ap)

Confusion Matrix:
 [[  0 105]
 [  0 104]]
Training accuracy:  0.49896907216494846
Testing  accuracy:  0.49760765550239233
Precision:  0.49760765550239233
Recall:  1.0
F1-Score:  0.6645367412140575
AUC:  0.5
Average Precision:  0.49760765550239233

In [101]:
y_test_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h3> Linear Classifier </h3>

In [ ]:
from sklearn.linear_model import SGDClassifier
model_1 = SGDClassifier(random_state=42,max_iter=1000,loss="log") 
model_1.fit(x_train,y_train)

In [ ]:
y_train

In [ ]:
y_test_pred = model_1.predict(x_test)
y_test_pred

In [ ]:
model_1.score(x_train, y_train)

In [ ]:
model_1.score(x_test, y_test)

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score,recall_score,precision_score
from sklearn.metrics import average_precision_score,roc_auc_score

y_test_pred = model_1.predict(x_test)
cfm = confusion_matrix(y_test,y_test_pred)

accuracy_training = model_1.score(x_train,y_train)
accuracy_testing = model_1.score(x_test,y_test)

precision = precision_score(y_test, y_test_pred)
recall = recall_score(y_test, y_test_pred)
f1 = f1_score(y_test, y_test_pred)

y_prob = model_1.predict_proba(x_test)[:,1]
auc = roc_auc_score(y_test, y_prob)

ap = average_precision_score(y_test, y_test_pred)

print("Confusion Matrix: \n",cfm)
print("Training accuracy: ",accuracy_training)
print("Testing  accuracy: ",accuracy_testing)
print("Precision: ",precision)
print("Recall: ",recall)
print("F1-Score: ",f1)
print("AUC: ",auc)
print("Average Precision: ", ap)

In [ ]:
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor
model_4 = RandomForestClassifier(n_estimators=100,max_depth=200,min_samples_leaf=5000,min_samples_split=4000)
model_4.fit(x_train,y_train)

In [ ]:
y_test_pred = model_4.predict(x_test)
y_test_pred

In [ ]:
x = stocks["AAPL"].iloc[:,1:-1].astype(float) 

y

In [ ]:
x

In [ ]:
stocks['AAPL'] = stocks['AAPL'].assign(y = y)
stocks['AAPL']['signal'] = stocks['AAPL']["y"].apply(lambda x: 0 if x <0 else 1)

In [ ]:
y = stocks['AAPL']['signal']

In [ ]:
from sklearn.model_selection import train_test_split
#Get x_train, x_test, y_train, y_test

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42)

#And check the shape
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model_4 = RandomForestClassifier(n_estimators=100,max_depth=200,min_samples_leaf=5000,min_samples_split=4000)
model_4.fit(x_train,y_train)

In [ ]:
y_test_pred = model_4.predict(x_test)
y_test_pred

In [ ]:
y_test